# docker-compose.yml

version: '3'

services:
  medusa-backend:
    build: .
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@localhost:5432/mydb
      - JWT_SECRET=your_jwt_secret
      - COOKIE_SECRET=your_cookie_secret
