name: Deploy Medusa Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ap-south-1  # Specify the AWS region here

      - name: Build and Push Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-ecr-repo  # Replace with your actual ECR repository name
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --push -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker buildx build --platform linux/amd64 --push -t $REGISTRY/$REPOSITORY:latest .

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster medusa-cluster \
          --service medusa-service \
          --region ap-south-1 \
          --force-new-deployment \
          --output json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

